### ISSUE TITLE
Webschema validation

### ISSUE THREAD

**Issue by toenuff** [toenuff/flancy#3]
new-flancy should probably have some validation on the webschema parameter.  It should be flexible (include additional props), but it probably needs to validate that it is a list and that each element in the list has a method, script, and path properties

**Comment by beatcracker** [comment]
FYI: I'm working on this (not sure that I can write tests though, but I'll try).

**Comment by toenuff** [comment]
good job - the tests worked great!  :+1:  Welcome to the project!  I'll merge with master once @adamdriscoll gets the token auth stuff worked out.
